### ISSUE TITLE
Expand IdentityFile path

### ISSUE THREAD

**Issue by agarzola** [usstudentloancenter/flightplan-sshconf#1]
Hello. A config file that looks like this:
```
Host example
  HostName [redacted_ip]
  IdentityFile ~/.ssh/private_key_name
  IdentitiesOnly yes
```

Gives me this error:
```
Error connecting to '[redacted_ip]': ENOENT: no such file or directory, open '~/.ssh/private_key_name
```

However, replacing `IdentityFile` value to an absolute path like so will fix it:
```
  IdentityFile /Users/agarzola/.ssh/private_key_name
```

I didn’t see a place in your source code (or `sshconfig`’s `parse()` method, for that matter) where this path is used to read a stream, but I could be missing something. I’m not sure what’s the right place to implement expanding this path (something like `path.join(value)`, I guess?), so I’d like your guidance on this.

BTW: This project is a lifesaver; thanks for putting it out there!

**Comment by theY4Kman** [comment]
Hey, cheers, man. I came from the world of [Fabric](http://fabfile.org), where all this was a given. It made development life so cheerful. Gotta spread it where you can :)

Anyway, this is one of those cases where grepping fails... because [the code is using `Object.assign`](https://github.com/usstudentloancenter/flightplan-sshconf/blob/master/lib/sshconf.js#L35). If it were me, I'd throw in the path resolving stuff for the `"IdentityFile"` key there. I may get to that in time, but I may completely forget about it. Though, I review and merge pull requests to release to npm religiously :)
